### ISSUE TITLE
Broken!

### ISSUE THREAD

**Issue by 2cool4u567** [thebigsmileXD/BedWars#39] opened 2019-10-17 00:36 UTC
Hello, its not working for me. It also breaks other plugins, here is the error in console. 
```
17.10 00:15:19 [Server] Server thread/CRITICAL Error: "Class 'xenialdan\gameapi\Game' not found" (EXCEPTION) in "plugins/BedWars-master/src/xenialdan/BedWars/Loader" at line 42
17.10 00:15:19 [Server] Server thread/DEBUG #0 vendor/pocketmine/spl/BaseClassLoader(126): include()
17.10 00:15:19 [Server] Server thread/DEBUG #1 (): BaseClassLoader->loadClass(string[24] xenialdan\BedWars\Loader)
17.10 00:15:19 [Server] Server thread/DEBUG #2 (): spl_autoload_call(string[24] xenialdan\BedWars\Loader)
17.10 00:15:19 [Server] Server thread/DEBUG #3 src/pocketmine/plugin/PluginManager(180): class_exists(string[24] xenialdan\BedWars\Loader, boolean 1)
17.10 00:15:19 [Server] Server thread/DEBUG #4 src/pocketmine/plugin/PluginManager(351): pocketmine\plugin\PluginManager->loadPlugin(string[69] /plugins/BedWars-master, array[1])
17.10 00:15:19 [Server] Server thread/DEBUG #5 plugins/PocketMine-DevTools.phar/src/DevTools/DevTools(71): pocketmine\plugin\PluginManager->loadPlugins(string[55] /plugins/, array[1])
17.10 00:15:19 [Server] Server thread/DEBUG #6 src/pocketmine/plugin/PluginBase(123): DevTools\DevTools->onEnable()
17.10 00:15:19 [Server] Server thread/DEBUG #7 src/pocketmine/plugin/PluginManager(580): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
17.10 00:15:19 [Server] Server thread/DEBUG #8 src/pocketmine/Server(2002): pocketmine\plugin\PluginManager->enablePlugin(object DevTools\DevTools)
17.10 00:15:19 [Server] Server thread/DEBUG #9 src/pocketmine/Server(1988): pocketmine\Server->enablePlugin(object DevTools\DevTools)
17.10 00:15:19 [Server] Server thread/DEBUG #10 src/pocketmine/Server(1728): pocketmine\Server->enablePlugins(integer 0)
17.10 00:15:19 [Server] Server thread/DEBUG #11 src/pocketmine/PocketMine(275): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[47] /, string[55] /plugins/)
17.10 00:15:19 [Server] Server thread/DEBUG #12 src/pocketmine/PocketMine(299): pocketmine\server()
17.10 00:15:19 [Server] Server thread/DEBUG #13 (1): require(string[107] phar:///PMMP-Latest-Stable.phar/sr)
```

**Comment by thebigsmileXD** [comment] 2019-10-17 23:22
Gameapi is not installed (virion)
Duplicate of some other issues. Get a phar from poggit

**Closed by thebigsmileXD** 2019-10-17 23:22 UTC
