### ISSUE TITLE
How to make bed?

### ISSUE THREAD

**Issue by coolbot123** [thebigsmileXD/BedWars#54] opened 2020-04-14 01:04 UTC
????

**Comment by thebigsmileXD** [comment] 2020-04-14 14:10
You take 3 Wool and 3 wooden planks and put them in a crafting table like this:
```
WWW
PPP
```
This will give you a bed.



---

Covered by 
Duplicate of #8 #51

**Closed** 2020-04-14 14:10 UTC
