### ISSUE TITLE
Doesn't Work

### ISSUE THREAD

**Issue by Ov3rPowerD** [thebigsmileXD/BedWars#66] opened 2020-06-16 05:41 UTC
I opened a **aternos** server recently and used the plug-in to make a **map**. I worked well until I tried to play it. When me and my friends clicked the sign, and error occurred saying: "Internal Error" please help.

**Comment by thebigsmileXD** [comment] 2020-06-16 07:15
Duplicate of #63 #65. Search before you open issues

**Closed by thebigsmileXD** 2020-06-16 07:15 UTC
