### ISSUE TITLE
Plugin not available

### ISSUE THREAD

**Issue by linmiao233** [thebigsmileXD/BedWars#40] opened 2019-11-02 01:30 UTC
[09:26:50] [Server thread/CRITICAL]: Error: "Class 'xenialdan\gameapi\Game' not found" (EXCEPTION) in "plugins/BedWars-master/src/xenialdan/BedWars/Loader" at line 42
[09:26:50] [Server thread/DEBUG]: #0 vendor/pocketmine/spl/BaseClassLoader(126): include()
[09:26:50] [Server thread/DEBUG]: #1 (): BaseClassLoader->loadClass(string[24] xenialdan\BedWars\Loader)
[09:26:50] [Server thread/DEBUG]: #2 (): spl_autoload_call(string[24] xenialdan\BedWars\Loader)
[09:26:50] [Server thread/DEBUG]: #3 src/pocketmine/plugin/PluginManager(180): class_exists(string[24] xenialdan\BedWars\Loader, boolean 1)
[09:26:50] [Server thread/DEBUG]: #4 src/pocketmine/plugin/PluginManager(351): pocketmine\plugin\PluginManager->loadPlugin(string[65] C:\Users\Administrator\Desktop\PM.........\plugins\BedWars-master, array[1])
[09:26:50] [Server thread/DEBUG]: #5 plugins/PocketMine-DevTools.phar/src/DevTools/DevTools(71): pocketmine\plugin\PluginManager->loadPlugins(string[51] C:\Users\Administrator\Desktop\PM.........\plugins\, array[1])
[09:26:50] [Server thread/DEBUG]: #6 src/pocketmine/plugin/PluginBase(123): DevTools\DevTools->onEnable()
[09:26:50] [Server thread/DEBUG]: #7 src/pocketmine/plugin/PluginManager(580): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
[09:26:50] [Server thread/DEBUG]: #8 src/pocketmine/Server(2008): pocketmine\plugin\PluginManager->enablePlugin(object DevTools\DevTools)
[09:26:50] [Server thread/DEBUG]: #9 src/pocketmine/Server(1994): pocketmine\Server->enablePlugin(object DevTools\DevTools)
[09:26:50] [Server thread/DEBUG]: #10 src/pocketmine/Server(1734): pocketmine\Server->enablePlugins(integer 0)
[09:26:50] [Server thread/DEBUG]: #11 src/pocketmine/PocketMine(275): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[43] C:\Users\Administrator\Desktop\PM.........\, string[51] C:\Users\Administrator\Desktop\PM.........\plugins\)
[09:26:50] [Server thread/DEBUG]: #12 src/pocketmine/PocketMine(299): pocketmine\server()
[09:26:50] [Server thread/DEBUG]: #13 (1): require(string[98] phar://C:/Users/Administrator/Desktop/PM........./PocketMine-MP.phar/src/pocketm)
[09:26:50] [Server thread/INFO]: 正在停用插件 DevTools v1.13.4

**Comment by thebigsmileXD** [comment] 2019-11-03 02:55
Duplicate of so many issues. Use search.

**Closed by thebigsmileXD** 2019-11-03 02:55 UTC
Labels: duplicate, invalid
