### ISSUE TITLE
"Internal server error" when joining (with join sign)

### ISSUE THREAD

**Issue by Phokiyu** [thebigsmileXD/BedWars#63] opened 2020-06-12 15:38 UTC
Hi !
I have a problem, when i try to join a bedwars game i created, i get "internal server error" ? Is this normal ? Because i did all, spawn, spawners, and shop villagers...

Help please !

Phokiyu

**Comment by thebigsmileXD** [comment] 2020-06-15 11:37
Give console output and plugin version

**Comment by Ov3rPowerD** [comment] 2020-06-16 05:44
[01:43:42] [Server thread/NOTICE]: USER removed
[01:43:42] [Server thread/INFO]: USER left the game
[01:43:42] [Server thread/INFO]: USER [/99.245.244.17:65299] logged out due to Internal server error
[01:43:42] [RakLibServer thread/NOTICE]: Blocked 99.245.244.17 for 5 seconds

**Comment by Ov3rPowerD** [comment] 2020-06-16 05:45
will this help

**Comment by Ov3rPowerD** [comment] 2020-06-16 05:50
BedWars v1.1.5

**Comment by thebigsmileXD** [comment] 2020-06-16 07:14
Enable debug level 2 ad provide log .-.

**Comment by thebigsmileXD** [comment] 2020-06-16 07:18
duplicate of #65

**Closed by thebigsmileXD** 2020-06-16 07:18 UTC
