### ISSUE TITLE
Please fix that

### ISSUE THREAD

**Issue by DaffyGutenTag** [thebigsmileXD/BedWars#22] opened 2019-08-14 10:51 UTC
The villagers turn back when the game is over and there is no food in the store. Can you make that the game starts if there are 2 players in the game?

**Comment by DaffyGutenTag** [comment] 2019-08-14 14:48
The Enderchest is cleared after a game!

**Comment by mote166** [comment] 2019-08-14 22:12
don't u have an issue with using the enchanted items on people? it doesn't crash ?

**Comment by thebigsmileXD** [comment] 2019-09-27 12:59
> The Enderchest is cleared after a game!
Duplicate of #11, See #15 
Closing as i am seperating the issues

**Closed by thebigsmileXD** 2019-09-27 12:59 UTC
Labels: State: Investigating, bug

**Comment by thebigsmileXD** [comment] 2019-09-27 13:01
> Can you make that the game starts if there are 2 players in the game?

Set up 2 teams only, and set minimun players to 1.

**Comment by thebigsmileXD** [comment] 2019-09-27 13:02
> The villagers turn back when the game is over

I have no idea what this is supposed to mean.
