### ISSUE TITLE
api error

### ISSUE THREAD

**Issue by vasilishunter** [thebigsmileXD/BedWars#42] opened 2019-11-15 19:37 UTC
Error: Class 'xenialdan\gameapi\Game' not found
File: plugins/BedWars-master/src/xenialdan/BedWars/Loader
Line: 42
Type: E_ERROR

**Comment by thebigsmileXD** [comment] 2019-11-15 21:06
Install gameapi. Duplicate of too many issues.

**Closed by thebigsmileXD** 2019-11-15 21:06 UTC

**Comment by vasilishunter** [comment] 2019-11-15 21:08
What do you mean install gameapi?
