### ISSUE TITLE
I am having multiple issues.

### ISSUE THREAD

**Issue by ange0770** [thebigsmileXD/BedWars#28] opened 2019-09-27 05:46 UTC
hello, i really like the simple concept of your plugin and would love to use it on my minecraft server :) i just have a few questions  i would like to ask.
1. the villagers from the villager shops move. they walk over the edge and they don’t stand still. this may be due to the fact i have a plugin that adds animals, but i’m not 100% sure.
2. i can’t activate the arena i set up. i made the sign correctly but when you click it, it doesn’t do anything. 
3. can i use copy and paste or will it not detect the block and not reset?
i hope you can respond x

**Comment by thebigsmileXD** [comment] 2019-09-27 12:50
Duplicate of #17, Duplicate of #20

**Closed by thebigsmileXD** 2019-09-27 12:50 UTC
