### ISSUE TITLE
Plugib

### ISSUE THREAD

**Issue by qaqapro** [thebigsmileXD/BedWars#56] opened 2020-04-17 17:02 UTC
Best plugin. But There is no bed setup

**Comment by thebigsmileXD** [comment] 2020-04-21 00:15
Bed setup = In map build mode, place beds. Break a bed to register the bed. Duplicate of #8

**Closed** 2020-04-21 00:23 UTC

**Comment by qaqapro** [comment] 2020-04-21 08:22
Dude i did it what you say but not working you can add this on  setup ui.
Plz help

21 Nis 2020 Sal 04:15 tarihinde XenialDan <notifications@github.com> şunu
yazdı:
