### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by GithubPaul1** [thebigsmileXD/BedWars#7] opened 2019-06-08 20:05 UTC
When activating the plugin, the following errors occur: 
[21:58:40] [Server thread/CRITICAL]: Error: "Class 'muqsit\invmenu\InvMenuHandler' not found" (EXCEPTION) in "plugins/BedWars_dev-2.phar/src/xenialdan/BedWars/Loader" at line 67
and: 
[21:58:40] [Server thread/CRITICAL]: TypeError: "Return value of xenialdan\BedWars\libs\xenialdan\gameapi\event\DefaultSettingsListener::getRegistrant() must be an instance of xenialdan\BedWars\libs\xenialdan\gameapi\Game, null returned" (EXCEPTION) in "plugins/BedWars_dev-2.phar/src/xenialdan/BedWars/libs/xenialdan/gameapi/event/DefaultSettingsListener" at line 43
Sorry for my bad english i'm  German

**Comment by thebigsmileXD** [comment] 2019-06-08 22:18
Duplicate of #3

**Closed by thebigsmileXD** 2019-06-08 22:18 UTC

**Comment by GithubPaul1** [comment] 2019-06-09 09:12
Oh, okay I did not see that there was an isue about these errors. should I install InvMenu and GameAPI?

**Comment by thebigsmileXD** [comment] 2019-06-09 11:56
Yes -.-

**Comment by GithubPaul1** [comment] 2019-06-09 12:44
But Gameapi has a error.

**Comment by GithubPaul1** [comment] 2019-06-09 16:34
But Gameapi and InvMenu are not loading. I use the phar.

**Comment by GithubPaul1** [comment] 2019-06-10 19:00
I have installed DEVirion and have created the folder virions and the virions as phar in the folder done. but they do not load and I still get both errors.

**Comment by thebigsmileXD** [comment] 2019-06-10 23:47
Installed gameapi, apibossbar, invmenu?

**Comment by GithubPaul1** [comment] 2019-06-11 09:19
For that I have to have DEVirion or not? I have DEVirion and have created the folder virions and the virions as phar in the folder done but they do not load. All three as phar in the virions folder. They do not load in the plugins folder either.

**Comment by thebigsmileXD** [comment] 2019-06-11 19:59
Tip: simply use the bedwars phar from poggit.

**Comment by GithubPaul1** [comment] 2019-06-12 08:48
I use the phar from poggit and get these errors.

**Comment by thebigsmileXD** [comment] 2019-06-12 15:12
Then you wouldn't have to install anything, since its already injected in  the phar.

Locking due to leading to nowhere.

**Comment by thebigsmileXD** [comment] 2019-06-12 16:00
Blame me. InvMenu was actually missing in .poggit.yml due to a crash of PHPStorm without saving. Fixed. #2 #3 #4 #5 #6 #7
